baseURL = "https://danielnordmark.se/"
defaultContentLanguage = "sv"
title = "Daniel Nordmark"
theme = "github.com/jpanther/congo/v2"

enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/jpanther/congo/v2"

[services]
  [services.rss]
    limit = 0

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]
